// Dane siedzib władz powiatów (wbudowane, bez zewnętrznego pliku źródłowego).
// Źródło: wykaz gmin i powiatów wchodzących w skład województw
// (Obwieszczenie Prezesa Rady Ministrów z 22.06.2001, M.P. 2001 poz. 325),
// zaktualizowany o zmiany podziału TERYT: powiat wałbrzyski zlikwidowany
// (2003), jeleniogórski -> karkonoski. Stan: 314 powiatów ziemskich
// + 66 miast na prawach powiatu = 380 (16 województw).
//
// Format: { "nazwa województwa małymi literami": [
//   ...["nazwa powiatu (małymi)", "Siedziba"],        // powiat ziemski
//   ...["Miasto na prawach powiatu"],                 // miasto: siedziba = nazwa
// ]}
export const SIEDZIBY_POWIATOW = {
  dolnośląskie: [
    ["Wrocław"],
    ["Legnica"],
    ["Jelenia Góra"],
    ["Wałbrzych"],
    ["wałbrzyski", "Wałbrzych"],
    ["bolesławiecki", "Bolesławiec"],
    ["dzierżoniowski", "Dzierżoniów"],
    ["głogowski", "Głogów"],
    ["górowski", "Góra"],
    ["jaworski", "Jawor"],
    ["karkonoski", "Jelenia Góra"],
    ["kamiennogórski", "Kamienna Góra"],
    ["kłodzki", "Kłodzko"],
    ["legnicki", "Legnica"],
    ["lubański", "Lubań"],
    ["lubiński", "Lubin"],
    ["lwówecki", "Lwówek Śląski"],
    ["milicki", "Milicz"],
    ["oleśnicki", "Oleśnica"],
    ["oławski", "Oława"],
    ["polkowicki", "Polkowice"],
    ["strzeliński", "Strzelin"],
    ["średzki", "Środa Śląska"],
    ["świdnicki", "Świdnica"],
    ["trzebnicki", "Trzebnica"],
    ["wołowski", "Wołów"],
    ["wrocławski", "Wrocław"],
    ["ząbkowicki", "Ząbkowice Śląskie"],
    ["zgorzelecki", "Zgorzelec"],
    ["złotoryjski", "Złotoryja"],
  ],
  "kujawsko-pomorskie": [
    ["Bydgoszcz"],
    ["Grudziądz"],
    ["Toruń"],
    ["Włocławek"],
    ["aleksandrowski", "Aleksandrów Kujawski"],
    ["brodnicki", "Brodnica"],
    ["bydgoski", "Bydgoszcz"],
    ["chełmiński", "Chełmno"],
    ["golubsko-dobrzyński", "Golub-Dobrzyń"],
    ["grudziądzki", "Grudziądz"],
    ["inowrocławski", "Inowrocław"],
    ["lipnowski", "Lipno"],
    ["mogileński", "Mogilno"],
    ["nakielski", "Nakło nad Notecią"],
    ["radziejowski", "Radziejów"],
    ["rypiński", "Rypin"],
    ["sępoleński", "Sępólno Krajeńskie"],
    ["świecki", "Świecie"],
    ["toruński", "Toruń"],
    ["tucholski", "Tuchola"],
    ["wąbrzeski", "Wąbrzeźno"],
    ["włocławski", "Włocławek"],
    ["żniński", "Żnin"],
  ],
  lubelskie: [
    ["Biała Podlaska"],
    ["Chełm"],
    ["Lublin"],
    ["Zamość"],
    ["bialski", "Biała Podlaska"],
    ["biłgorajski", "Biłgoraj"],
    ["chełmski", "Chełm"],
    ["hrubieszowski", "Hrubieszów"],
    ["janowski", "Janów Lubelski"],
    ["krasnostawski", "Krasnystaw"],
    ["kraśnicki", "Kraśnik"],
    ["lubartowski", "Lubartów"],
    ["lubelski", "Lublin"],
    ["łęczyński", "Łęczna"],
    ["łukowski", "Łuków"],
    ["opolski", "Opole Lubelskie"],
    ["parczewski", "Parczew"],
    ["puławski", "Puławy"],
    ["radzyński", "Radzyń Podlaski"],
    ["rycki", "Ryki"],
    ["świdnicki", "Świdnik"],
    ["tomaszowski", "Tomaszów Lubelski"],
    ["włodawski", "Włodawa"],
    ["zamojski", "Zamość"],
  ],
  lubuskie: [
    ["Gorzów Wielkopolski"],
    ["Zielona Góra"],
    ["gorzowski", "Gorzów Wielkopolski"],
    ["krośnieński", "Krosno Odrzańskie"],
    ["międzyrzecki", "Międzyrzecz"],
    ["nowosolski", "Nowa Sól"],
    ["słubicki", "Słubice"],
    ["strzelecko-drezdenecki", "Drezdenko"],
    ["sulęciński", "Sulęcin"],
    ["świebodziński", "Świebodzin"],
    ["wschowski", "Wschowa"],
    ["zielonogórski", "Zielona Góra"],
    ["żagański", "Żagań"],
    ["żarski", "Żary"],
  ],
  łódzkie: [
    ["Łódź"],
    ["Piotrków Trybunalski"],
    ["Skierniewice"],
    ["brzeziński", "Brzeziny"],
    ["bełchatowski", "Bełchatów"],
    ["kutnowski", "Kutno"],
    ["łaski", "Łask"],
    ["łęczycki", "Łęczyca"],
    ["łowicki", "Łowicz"],
    ["łódzki wschodni", "Łódź"],
    ["opoczyński", "Opoczno"],
    ["pabianicki", "Pabianice"],
    ["pajęczański", "Pajęczno"],
    ["piotrkowski", "Piotrków Trybunalski"],
    ["poddębicki", "Poddębice"],
    ["radomszczański", "Radomsko"],
    ["rawski", "Rawa Mazowiecka"],
    ["sieradzki", "Sieradz"],
    ["skierniewicki", "Skierniewice"],
    ["tomaszowski", "Tomaszów Mazowiecki"],
    ["wieluński", "Wieluń"],
    ["wieruszowski", "Wieruszów"],
    ["zduńskowolski", "Zduńska Wola"],
    ["zgierski", "Zgierz"],
  ],
  małopolskie: [
    ["Kraków"],
    ["Nowy Sącz"],
    ["Tarnów"],
    ["bocheński", "Bochnia"],
    ["brzeski", "Brzesko"],
    ["chrzanowski", "Chrzanów"],
    ["dąbrowski", "Dąbrowa Tarnowska"],
    ["gorlicki", "Gorlice"],
    ["krakowski", "Kraków"],
    ["limanowski", "Limanowa"],
    ["miechowski", "Miechów"],
    ["myślenicki", "Myślenice"],
    ["nowosądecki", "Nowy Sącz"],
    ["nowotarski", "Nowy Targ"],
    ["olkuski", "Olkusz"],
    ["oświęcimski", "Oświęcim"],
    ["proszowicki", "Proszowice"],
    ["suski", "Sucha Beskidzka"],
    ["tarnowski", "Tarnów"],
    ["tatrzański", "Zakopane"],
    ["wadowicki", "Wadowice"],
    ["wielicki", "Wieliczka"],
  ],
  mazowieckie: [
    ["Ostrołęka"],
    ["Płock"],
    ["Radom"],
    ["Siedlce"],
    ["Warszawa"],
    ["białobrzeski", "Białobrzegi"],
    ["ciechanowski", "Ciechanów"],
    ["garwoliński", "Garwolin"],
    ["gostyniński", "Gostynin"],
    ["grodziski", "Grodzisk Mazowiecki"],
    ["grójecki", "Grójec"],
    ["kozienicki", "Kozienice"],
    ["legionowski", "Legionowo"],
    ["lipski", "Lipsko"],
    ["łosicki", "Łosice"],
    ["makowski", "Maków Mazowiecki"],
    ["miński", "Mińsk Mazowiecki"],
    ["mławski", "Mława"],
    ["nowodworski", "Nowy Dwór Mazowiecki"],
    ["ostrołęcki", "Ostrołęka"],
    ["ostrowski", "Ostrów Mazowiecka"],
    ["otwocki", "Otwock"],
    ["piaseczyński", "Piaseczno"],
    ["płocki", "Płock"],
    ["płoński", "Płońsk"],
    ["pruszkowski", "Pruszków"],
    ["przasnyski", "Przasnysz"],
    ["przysuski", "Przysucha"],
    ["pułtuski", "Pułtusk"],
    ["radomski", "Radom"],
    ["siedlecki", "Siedlce"],
    ["sierpecki", "Sierpc"],
    ["sochaczewski", "Sochaczew"],
    ["sokołowski", "Sokołów Podlaski"],
    ["szydłowiecki", "Szydłowiec"],
    ["warszawski zachodni", "Ożarów Mazowiecki"],
    ["węgrowski", "Węgrów"],
    ["wołomiński", "Wołomin"],
    ["wyszkowski", "Wyszków"],
    ["zwoleński", "Zwoleń"],
    ["żuromiński", "Żuromin"],
    ["żyrardowski", "Żyrardów"],
  ],
  opolskie: [
    ["Opole"],
    ["brzeski", "Brzeg"],
    ["głubczycki", "Głubczyce"],
    ["kędzierzyńsko-kozielski", "Kędzierzyn-Koźle"],
    ["kluczborski", "Kluczbork"],
    ["krapkowicki", "Krapkowice"],
    ["namysłowski", "Namysłów"],
    ["nyski", "Nysa"],
    ["oleski", "Olesno"],
    ["opolski", "Opole"],
    ["prudnicki", "Prudnik"],
    ["strzelecki", "Strzelce Opolskie"],
  ],
  podkarpackie: [
    ["Krosno"],
    ["Przemyśl"],
    ["Rzeszów"],
    ["Tarnobrzeg"],
    ["bieszczadzki", "Ustrzyki Dolne"],
    ["brzozowski", "Brzozów"],
    ["dębicki", "Dębica"],
    ["jarosławski", "Jarosław"],
    ["jasielski", "Jasło"],
    ["kolbuszowski", "Kolbuszowa"],
    ["krośnieński", "Krosno"],
    ["leski", "Lesko"],
    ["leżajski", "Leżajsk"],
    ["lubaczowski", "Lubaczów"],
    ["łańcucki", "Łańcut"],
    ["mielecki", "Mielec"],
    ["niżański", "Nisko"],
    ["przemyski", "Przemyśl"],
    ["przeworski", "Przeworsk"],
    ["ropczycko-sędziszowski", "Ropczyce"],
    ["rzeszowski", "Rzeszów"],
    ["sanocki", "Sanok"],
    ["stalowowolski", "Stalowa Wola"],
    ["strzyżowski", "Strzyżów"],
    ["tarnobrzeski", "Tarnobrzeg"],
  ],
  podlaskie: [
    ["Białystok"],
    ["Łomża"],
    ["Suwałki"],
    ["augustowski", "Augustów"],
    ["białostocki", "Białystok"],
    ["bielski", "Bielsk Podlaski"],
    ["grajewski", "Grajewo"],
    ["hajnowski", "Hajnówka"],
    ["kolneński", "Kolno"],
    ["łomżyński", "Łomża"],
    ["moniecki", "Goniądz"],
    ["sejneński", "Sejny"],
    ["siemiatycki", "Siemiatycze"],
    ["sokólski", "Sokółka"],
    ["suwalski", "Suwałki"],
    ["wysokomazowiecki", "Wysokie Mazowieckie"],
    ["zambrowski", "Zambrów"],
  ],
  pomorskie: [
    ["Gdańsk"],
    ["Gdynia"],
    ["Słupsk"],
    ["Sopot"],
    ["bytowski", "Bytów"],
    ["chojnicki", "Chojnice"],
    ["człuchowski", "Człuchów"],
    ["gdański", "Gdańsk"],
    ["kartuski", "Kartuzy"],
    ["kościerski", "Kościerzyna"],
    ["kwidzyński", "Kwidzyn"],
    ["lęborski", "Lębork"],
    ["malborski", "Malbork"],
    ["nowodworski", "Nowy Dwór Gdański"],
    ["pucki", "Puck"],
    ["słupski", "Słupsk"],
    ["starogardzki", "Starogard Gdański"],
    ["sztumski", "Sztum"],
    ["tczewski", "Tczew"],
    ["wejherowski", "Wejherowo"],
  ],
  śląskie: [
    ["Bielsko-Biała"],
    ["Bytom"],
    ["Chorzów"],
    ["Częstochowa"],
    ["Dąbrowa Górnicza"],
    ["Gliwice"],
    ["Jastrzębie-Zdrój"],
    ["Jaworzno"],
    ["Katowice"],
    ["Mysłowice"],
    ["Piekary Śląskie"],
    ["Ruda Śląska"],
    ["Rybnik"],
    ["Siemianowice Śląskie"],
    ["Sosnowiec"],
    ["Świętochłowice"],
    ["Tychy"],
    ["Zabrze"],
    ["Żory"],
    ["będziński", "Będzin"],
    ["bielski", "Bielsko-Biała"],
    ["cieszyński", "Cieszyn"],
    ["częstochowski", "Częstochowa"],
    ["gliwicki", "Gliwice"],
    ["kłobucki", "Kłobuck"],
    ["lubliniecki", "Lubliniec"],
    ["mikołowski", "Mikołów"],
    ["myszkowski", "Myszków"],
    ["pszczyński", "Pszczyna"],
    ["raciborski", "Racibórz"],
    ["rybnicki", "Rybnik"],
    ["tarnogórski", "Tarnowskie Góry"],
    ["bieruńsko-lędziński", "Bieruń"],
    ["wodzisławski", "Wodzisław Śląski"],
    ["zawierciański", "Zawiercie"],
    ["żywiecki", "Żywiec"],
  ],
  świętokrzyskie: [
    ["Kielce"],
    ["buski", "Busko-Zdrój"],
    ["jędrzejowski", "Jędrzejów"],
    ["kazimierski", "Kazimierza Wielka"],
    ["kielecki", "Kielce"],
    ["konecki", "Końskie"],
    ["opatowski", "Opatów"],
    ["ostrowiecki", "Ostrowiec Świętokrzyski"],
    ["pińczowski", "Pińczów"],
    ["sandomierski", "Sandomierz"],
    ["skarżyski", "Skarżysko-Kamienna"],
    ["starachowicki", "Starachowice"],
    ["staszowski", "Staszów"],
    ["włoszczowski", "Włoszczowa"],
  ],
  "warmińsko-mazurskie": [
    ["Elbląg"],
    ["Olsztyn"],
    ["bartoszycki", "Bartoszyce"],
    ["braniewski", "Braniewo"],
    ["działdowski", "Działdowo"],
    ["elbląski", "Elbląg"],
    ["ełcki", "Ełk"],
    ["giżycki", "Giżycko"],
    ["iławski", "Iława"],
    ["kętrzyński", "Kętrzyn"],
    ["lidzbarski", "Lidzbark Warmiński"],
    ["mrągowski", "Mrągowo"],
    ["nidzicki", "Nidzica"],
    ["nowomiejski", "Nowe Miasto Lubawskie"],
    ["olecki", "Olecko"],
    ["gołdapski", "Gołdap"],
    ["olsztyński", "Olsztyn"],
    ["ostródzki", "Ostróda"],
    ["piski", "Pisz"],
    ["szczycieński", "Szczytno"],
    ["węgorzewski", "Węgorzewo"],
  ],
  wielkopolskie: [
    ["Kalisz"],
    ["Konin"],
    ["Leszno"],
    ["Poznań"],
    ["chodzieski", "Chodzież"],
    ["czarnkowsko-trzcianecki", "Czarnków"],
    ["gnieźnieński", "Gniezno"],
    ["gostyński", "Gostyń"],
    ["grodziski", "Grodzisk Wielkopolski"],
    ["jarociński", "Jarocin"],
    ["kaliski", "Kalisz"],
    ["kępiński", "Kępno"],
    ["kolski", "Koło"],
    ["koniński", "Konin"],
    ["kościański", "Kościan"],
    ["krotoszyński", "Krotoszyn"],
    ["leszczyński", "Leszno"],
    ["międzychodzki", "Międzychód"],
    ["nowotomyski", "Nowy Tomyśl"],
    ["obornicki", "Oborniki"],
    ["ostrowski", "Ostrów Wielkopolski"],
    ["ostrzeszowski", "Ostrzeszów"],
    ["pilski", "Piła"],
    ["pleszewski", "Pleszew"],
    ["poznański", "Poznań"],
    ["rawicki", "Rawicz"],
    ["słupecki", "Słupca"],
    ["szamotulski", "Szamotuły"],
    ["średzki", "Środa Wielkopolska"],
    ["śremski", "Śrem"],
    ["turecki", "Turek"],
    ["wągrowiecki", "Wągrowiec"],
    ["wolsztyński", "Wolsztyn"],
    ["wrzesiński", "Września"],
    ["złotowski", "Złotów"],
  ],
  zachodniopomorskie: [
    ["Koszalin"],
    ["Szczecin"],
    ["Świnoujście"],
    ["białogardzki", "Białogard"],
    ["choszczeński", "Choszczno"],
    ["drawski", "Drawsko Pomorskie"],
    ["goleniowski", "Goleniów"],
    ["gryficki", "Gryfice"],
    ["gryfiński", "Gryfino"],
    ["kamieński", "Kamień Pomorski"],
    ["kołobrzeski", "Kołobrzeg"],
    ["koszaliński", "Koszalin"],
    ["łobeski", "Łobez"],
    ["myśliborski", "Myślibórz"],
    ["policki", "Police"],
    ["pyrzycki", "Pyrzyce"],
    ["sławieński", "Sławno"],
    ["stargardzki", "Stargard"],
    ["szczecinecki", "Szczecinek"],
    ["świdwiński", "Świdwin"],
    ["wałecki", "Wałcz"],
  ],
};
